albums:
    type:     rest
    resource: "@GalleryBundle/Controller/AlbumsController.php"

photos:
    type:     rest
    parent:   albums
    resource: "@GalleryBundle/Controller/PhotosController.php"
    name_prefix: api_